<?php
// $Id$

/**
 * @file
 * A user interface for searching and browsing through multiple facets.
 */

require_once('./'. drupal_get_path('module', 'faceted_search') .'/faceted_search.inc');

/**
 * Global. The current search environments. When set, this is an array keyed by
 * environment id.
 */
$faceted_search = NULL;

/**
 * Implementation of hook_perm().
 */
function faceted_search_ui_perm() {
  return array('use faceted search');
}

/**
 * Implementation of hook_menu().
 */
function faceted_search_ui_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    foreach (faceted_search_get_env_ids() as $env_id) {
      $base_path = faceted_search_variable_get($env_id, 'base_path', ''); 
      $items[] = array(
        'path' => $base_path,
        'title' => check_plain(faceted_search_variable_get($env_id, 'title', t('Search'))), // Needed for breadcrumb.
        'callback' => 'faceted_search_ui_stage_select',
        'callback arguments' => array($env_id),
        'access' => user_access('use faceted search'),
        'type' => MENU_CALLBACK,
      );
      $items[] = array(
        'path' => $base_path .'/results',
        'callback' => 'faceted_search_ui_stage_results',
        'callback arguments' => array($env_id),
        'access' => user_access('use faceted search'),
        'type' => MENU_CALLBACK,
      );
      $items[] = array(
        'path' => $base_path .'/facet',
        'callback' => 'faceted_search_ui_stage_facet',
        'callback arguments' => array($env_id),
        'access' => user_access('use faceted search'),
        'type' => MENU_CALLBACK,
      );
      $items[] = array(
        'path' => $base_path .'/categories',
        'callback' => 'faceted_search_ui_stage_categories',
        'callback arguments' => array($env_id),
        'access' => user_access('use faceted search'),
        'type' => MENU_CALLBACK,
      );
    }

    // TODO: Per-environment access control setting (à la Views). Then, will no
    // longer need the 'use faceted search' permission.
  }
  
  return $items;
}

/**
 * Implementation of hook_block().
 */
function faceted_search_ui_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    foreach (faceted_search_get_env_ids() as $env_id) {
      $env = faceted_search_variable_get($env_id, 'name', $env_id);
      if (faceted_search_variable_get($env_id, 'current_block', TRUE)) {
        $blocks[$env_id .'_current'] = array('info' => t('@env - Current search', array('@env' => $env)));
      }
      if (faceted_search_variable_get($env_id, 'keyword_block', TRUE)) {
        $blocks[$env_id .'_keyword'] = array('info' => t('@env - Keyword search', array('@env' => $env)));
      }
      if (faceted_search_variable_get($env_id, 'guided_block', TRUE)) {
        $blocks[$env_id .'_guided'] = array('info' => t('@env - Guided search', array('@env' => $env)));
      }
      if (faceted_search_variable_get($env_id, 'related_block', TRUE)) {
        $blocks[$env_id .'_related'] = array('info' => t('@env - Related categories', array('@env' => $env)));
      }
      if (faceted_search_variable_get($env_id, 'sort_block', TRUE)) {
        $blocks[$env_id .'_sort'] = array('info' => t('@env - Sort options', array('@env' => $env)));
      }
    }
    return $blocks;
  }
  elseif ($op == 'view' && user_access('use faceted search')) {
    global $faceted_search;
    
    // Determine the environment id and requested block.
    list($env_id, $delta) = explode('_', $delta, 2);

    if (!isset($faceted_search[$env_id]) && $delta != 'related') {
      // Initialize the current search. This case only happens when the block
      // does not appear directly on a Faceted Search page.
      $faceted_search[$env_id] = new faceted_search($env_id);
      $faceted_search[$env_id]->ui_state = _faceted_search_ui_defaults();
    }
    
    faceted_search_ui_add_css();
    switch ($delta) {
      case 'current':
        $block['subject'] = t('Current search'); 
        $block['content'] = faceted_search_ui_current_block($faceted_search[$env_id]);
        break;

      case 'keyword':
        if ($faceted_search[$env_id]->ui_state['stage'] == 'results') {
          $block['subject'] = t('Keyword search'); 
          $block['content'] = faceted_search_ui_keyword_block($faceted_search[$env_id]);
        }
        break;

      case 'guided':
        if ($faceted_search[$env_id]->ui_state['stage'] == 'results') {
          $block['subject'] = t('Guided search');
          $block['content'] = faceted_search_ui_guided_block($faceted_search[$env_id]);
        }
        break;

      case 'related':
        if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2) && $node = node_load(arg(1))) {
          $block['subject'] = t('Related categories'); 
          $block['content'] = faceted_search_ui_related_block($env_id, $node);
        }
        break;

      case 'sort':
        $block['content'] = faceted_search_ui_sort_block($faceted_search[$env_id]);
        break;
    }
    return $block;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function faceted_search_ui_form_alter($form_id, &$form) {
  if ($form_id == 'faceted_search_edit_form') {
    $env_id = $form['env_id']['#value'];

    // Basic information section.
    $base_path = faceted_search_variable_get($env_id, 'base_path', '');
    $form['info']['base_path'] = array( // TODO: Proper validation of the path.
      '#type' => 'textfield',
      '#title' => t('Base path'),
      '#default_value' => $base_path,
      '#required' => TRUE,
      '#description' => t('The base path under which this faceted search environment will be accessed. All faceted search links will be derived from that base path. Do not begin or end the base path with a /.'), 
    );
    $form['info']['start_page'] = array( // TODO: Proper validation of the path.
      '#type' => 'textfield',
      '#title' => t('Start page'),
      '#required' => TRUE,
      '#default_value' => faceted_search_variable_get($env_id, 'start_page', $base_path),
      '#description' => t("Path to go to when the current search is cleared. Popular options are the base path as entered above (shows a full search page), the base path followed by <code>/results</code> (shows all content using the same display style as search results), and <code>&lt;front&gt;</code> (goes to your site's front page). Do not begin or end the start page's path with a /."),
    );
    
    // Results page section.
    $form['results'] = array(
      '#type' => 'fieldset',
      '#title' => t('Results page'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    $styles = faceted_search_ui_style_list();
    $options = array();
    foreach ($styles as $key => $style) {
      $options[$key] = $style->get_label();
    }
    $form['results']['results_style'] = array(
      '#type' => 'select',
      '#title' => t('Display style'),
      '#options' => $options,
      '#default_value' => faceted_search_variable_get($env_id, 'results_style', 'faceted_search_ui:teasers'),
      '#description' => t('When the <em>Extracts</em> option is selected, search results show extracts relevant to the search keywords. With the <em>Teasers</em> option, search results use standard teasers. Other modules may provide additional display styles.'),
    );
    $form['results']['results_style_selective_extracts'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use the <em>Extracts</em> display style selectively.'),
      '#default_value' => faceted_search_variable_get($env_id, 'results_style_selective_extracts', TRUE),
      '#description' => t('If this is enabled, search results will be shown in the <em>Extracts</em> display style when the current search uses keywords, or use the above display style otherwise.'),
    );

    // Current search block section.
    $form['current'] = array(
      '#type' => 'fieldset',
      '#title' => t('Current search'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['current']['current_block'] = array(
      '#type' => 'checkbox',
      '#title' => t('Provide Current search block'),
      '#default_value' => faceted_search_variable_get($env_id, 'current_block', TRUE),
      '#description' => t('When enabled, this block appears when search terms have been entered. This block can only appear on Faceted Search pages. Block visibility settings may define additional conditions for this block to appear.'),
    );

    // Keyword search block section.
    $form['keyword'] = array(
      '#type' => 'fieldset',
      '#title' => t('Keyword search'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['keyword']['keyword_block'] = array(
      '#type' => 'checkbox',
      '#title' => t('Provide Keyword search block'),
      '#default_value' => faceted_search_variable_get($env_id, 'keyword_block', TRUE),
      '#description' => t('When enabled, this block provides a form where a search text can be entered. Block visibility settings may define additional conditions for this block to appear.'),
    );
    $form['keyword']['keyword_mode'] = array(
      '#type' => 'radios',
      '#title' => t('Default mode'),
      '#description' => t("Choose the mode to select by default in keyword search. <em>New search</em> might be more intuitive to users not familiar with Faceted Search's interface since it mimics most search engines."),
      '#default_value' => faceted_search_variable_get($env_id, 'keyword_mode', 'new'),
      '#options' => array('new' => t('New search'), 'refine' => t('Search within results')),
    );

    // Guided search block section.
    $form['guided'] = array(
      '#type' => 'fieldset',
      '#title' => t('Guided search'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['guided']['guided_block'] = array(
      '#type' => 'checkbox',
      '#title' => t('Provide Guided search block'),
      '#default_value' => faceted_search_variable_get($env_id, 'guided_block', TRUE),
      '#description' => t('When enabled, this block shows categories that may be selected to start or refine a search. Block visibility settings may define additional conditions for this block to appear.'),
    );
    $form['guided']['sort_block'] = array(
      '#type' => 'checkbox',
      '#title' => t('Provide Sort options block'),
      '#default_value' => faceted_search_variable_get($env_id, 'sort_block', TRUE),
      '#description' => t('When enabled, this block appears when navigating a full-page list of categories (after clicking the <em>More</em> link of a facet in the Guided search). Block visibility settings may define additional conditions for this block to appear.'),
    );
    $form['guided']['tooltips'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show tooltips on categories'),
      '#description' => t('Check this option to have tooltips displayed with subcategories when hovering over a category in the Guided search. This feature works only with clients that have JavaScript enabled, but is unobtrusive to clients that lack JavaScript.'),
      '#default_value' => faceted_search_variable_get($env_id, 'tooltips', FALSE),
    );

    // Related categories block section.
    $form['related'] = array(
      '#type' => 'fieldset',
      '#title' => t('Related categories'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['related']['related_block'] = array(
      '#type' => 'checkbox',
      '#title' => t('Provide Related categories block'),
      '#default_value' => faceted_search_variable_get($env_id, 'related_block', TRUE),
      '#description' => t('When enabled, this block appears on a node\'s full page, showing categories related to that node. Categories may be selected to start a search. This block only appears for node types allowed in the faceted search environment (see the <em>Basic information</em> section). Block visibility settings may define additional conditions for this block to appear.'),
    );
    $form['related']['related_style'] = array(
      '#type' => 'select',
      '#title' => t('Display style'),
      '#options' => array(
        'list_ungrouped' => t('List - Ungrouped'),
        'list_grouped' => t('List - Grouped by facet'),
        'table' => t('Table - Grouped by facet'),
      ),
      '#default_value' => faceted_search_variable_get($env_id, 'related_style', 'list_ungrouped'),
      '#description' => t('Related categories may be grouped by facet (useful when a node uses more than one category per facet), or ungrouped (flat list of categories).'),
    );
  }
}

/**
 * Implementation of hook_faceted_search_query_alter.
 *
 * Give the display style object an opportunity at altering the search
 * query. The style might, for example, require additional filtering or extra
 * fields.
 */
function faceted_search_ui_faceted_search_query_alter($search, &$query) {
  $styles = faceted_search_ui_style_list();
  $style = faceted_search_ui_get_style($search);
  if (method_exists($styles[$style], 'query_alter')) {
    $styles[$style]->query_alter($query, $search);
  }
}

/**
 * Menu callback to show the current search results.
 *
 * @param $env_id
 *   The environment into which the search is taking place.
 * @param $text
 *   The search text.
 */
function faceted_search_ui_stage_results($env_id, $text = '') {
  global $faceted_search;

  // If the menu system has splitted the search text because of slashes, glue it back.
  if (func_num_args() > 2) {
    $args = func_get_args();
    $text .= '/'. implode('/', array_slice($args, 2));
  }

  // Initialize the current search.
  $faceted_search[$env_id] = new faceted_search($env_id, $text);
  $faceted_search[$env_id]->ui_state = _faceted_search_ui_defaults();
  $faceted_search[$env_id]->ui_state['stage'] = 'results';
  
  if ($text) {
    // Log the search text.
    $path = faceted_search_ui_build_path($env_id, $faceted_search[$env_id]->ui_state, $text);
    watchdog('faceted_search', t('%text.', array('%text' => $text)), WATCHDOG_NOTICE, l(t('results'), $path));
  }

  faceted_search_ui_add_css();
    
  // Collect the search results.
  $faceted_search[$env_id]->execute();
  $results = faceted_search_ui_format_results($faceted_search[$env_id]);
    
  faceted_search_ui_set_title($faceted_search[$env_id]);
  $content = theme('faceted_search_ui_stage_results', $results);
  return theme('faceted_search_ui_page', $faceted_search[$env_id], $content);
}

/**
 * Implementation of hook_faceted_search_ui_style_info().
 */
function faceted_search_ui_faceted_search_ui_style_info() {
  return array(
    'extracts' => new faceted_search_ui_extract_style,
    'teasers' => new faceted_search_ui_teaser_style,
  );
}

/**
 * Menu callback to display the search page.
 */
function faceted_search_ui_stage_select($env_id, $text = '') {
  global $faceted_search;

  // If the menu system has splitted the search text because of slashes, glue it back.
  if (func_num_args() > 2) {
    $args = func_get_args();
    $text .= '/'. implode('/', array_slice($args, 2));
  }

  // Initialize the current search.
  $faceted_search[$env_id] = new faceted_search($env_id, $text);
  $faceted_search[$env_id]->ui_state = _faceted_search_ui_defaults();
  $faceted_search[$env_id]->ui_state['stage'] = 'select';
  
  faceted_search_ui_add_css();
    
  // Build the search results, which are required to count nodes per category
  $faceted_search[$env_id]->execute();

  faceted_search_ui_set_title($faceted_search[$env_id]);

  $keyword_block_content = faceted_search_ui_keyword_block($faceted_search[$env_id]);
  $guided_block_content = faceted_search_ui_guided_block($faceted_search[$env_id]);
  if ($output = theme('faceted_search_ui_stage_select', $faceted_search[$env_id], $keyword_block_content, $guided_block_content)) {
    return theme('faceted_search_ui_page', $faceted_search[$env_id], $output);
  }
}

/**
 * Menu callback to display a facet's categories.
 */
function faceted_search_ui_stage_facet($env_id, $facet_key_id = '', $facet_sort = '', $text = '') {
  global $faceted_search;

  if (!$facet_key_id || !$facet_sort) {
    drupal_not_found();
    return;
  }
  
  // If the menu system has splitted the search text because of slashes, glue it back.
  if (func_num_args() > 4) {
    $args = func_get_args();
    $text .= '/'. implode('/', array_slice($args, 4));
  }

  // Initialize the current search.
  $faceted_search[$env_id] = new faceted_search($env_id, $text);
  $faceted_search[$env_id]->ui_state = _faceted_search_ui_defaults();
  $faceted_search[$env_id]->ui_state['stage'] = 'facet';
  list($facet_key, $facet_id) = explode(':', $facet_key_id, 2);
  $faceted_search[$env_id]->ui_state['facet-key'] = $facet_key;
  $faceted_search[$env_id]->ui_state['facet-id'] = $facet_id;
  $faceted_search[$env_id]->ui_state['facet-sort'] = $facet_sort;
  
  faceted_search_ui_add_css();
  faceted_search_ui_add_tooltips($env_id);
  
  // Build the search results, which are required to count nodes per category
  $faceted_search[$env_id]->execute();

  // Find what facet to show
  list($index, $facet) = $faceted_search[$env_id]->get_facet_by_id($facet_key, $facet_id);
  if (!isset($index) || !isset($facet)) {
    drupal_not_found();
    return;
  }

  faceted_search_ui_set_title($faceted_search[$env_id]);
  $categories = faceted_search_ui_build_categories($faceted_search[$env_id], $index); // TODO: paging
  return theme('faceted_search_ui_stage_facet', $faceted_search[$env_id], $index, $facet, $categories);
}

/**
 * Menu callback to display an HTML chunk with categories related to a given
 * facet (using AJAX).
 */
function faceted_search_ui_stage_categories($env_id, $facet_key_id = '', $facet_sort = '', $text = '') {
  global $faceted_search;

  if (!$facet_key_id || !$facet_sort) {
    exit();
  }
  
  // If the menu system has splitted the search text because of slashes, glue it back.
  if (func_num_args() > 4) {
    $args = func_get_args();
    $text .= '/'. implode('/', array_slice($args, 4));
  }
  
  // Initialize the current search.
  $faceted_search[$env_id] = new faceted_search($env_id, $text);
  $faceted_search[$env_id]->ui_state = _faceted_search_ui_defaults();
  $faceted_search[$env_id]->ui_state['stage'] = 'categories';
  list($facet_key, $facet_id) = explode(':', $facet_key_id, 2);
  $faceted_search[$env_id]->ui_state['facet-key'] = $facet_key;
  $faceted_search[$env_id]->ui_state['facet-id'] = $facet_id;
  $faceted_search[$env_id]->ui_state['facet-sort'] = $facet_sort;

  // We are returning JavaScript, so tell the browser.
  drupal_set_header('Content-Type: text/javascript; charset=utf-8');
  
  // Build the search results, which are required to count nodes per category
  $faceted_search[$env_id]->execute();

  // Find what facet to show
  $found = FALSE;
  $facets = $faceted_search[$env_id]->get_facets();
  foreach ($facets as $index => $facet) {
    if ($facet->get_key() == $facet_key && $facet->get_id() == $facet_id) {
      $found = TRUE;
      break; // Found
    }
  }
  if (!$found) {
    exit();
  }

  if ($facet->get_max_categories() > 0) {
    $max_count = $facet->get_max_categories();
  }
  else {
    $max_count = NULL; // No limit.
  }

  // Prepare the HTML chunk
  $categories = faceted_search_ui_build_categories($faceted_search[$env_id], $index, 0, $max_count, FALSE);
  if (count($categories)) {
    $content = '<p>'. t('Subcategories:') .'</p>';
    $content .= theme('faceted_search_ui_categories', $facet, $categories, 'categories');
  }
  else {
    $content = '<p>'. t('No subcategories.') .'</p>'; 
  }
  $content = theme('faceted_search_ui_facet_wrapper', $env_id, $facet, 'categories', $content);

  // Output JSON data, with id to help client to cache the content.
  print drupal_to_js(
    array(
      'id' => $faceted_search[$env_id]->get_text(),
      'content' => $content,
    )
  );
  exit();
}

/**
 * Display the current search arguments.
 */
function faceted_search_ui_current_block($search) {
  if (!$search->get_text()) {
    return; // No current search
  }

  foreach ($search->get_facets() as $index => $facet) {
    if ($facet->is_active()) {
      $content = theme('faceted_search_ui_facet_heading', $search->get_env_id(), $search->ui_state, $search->get_facets(), $index, 'current');
      $output .= theme('faceted_search_ui_facet_wrapper', $search->get_env_id(), $facet, 'current', $content);
    }
  }
  
  return $output;
}

/**
 * Display the keyword search form.
 */
function faceted_search_ui_keyword_block($search) {
  return drupal_get_form('faceted_search_ui_form', $search);
}

/**
 * Display the faceted browser.
 */
function faceted_search_ui_guided_block($search) {
  faceted_search_ui_add_tooltips($search->get_env_id());
  
  $facet_content = array();
  foreach ($search->get_facets() as $index => $facet) {
    if ($facet->get_key() == 'keyword') {
      // Keyword "facets" are ignored in guided search.
      continue; 
    }

    if ($facet->get_max_categories() > 0) {
      $max_count = $facet->get_max_categories();
    }
    else {
      $max_count = NULL; // No limit.
    }
    
    $categories = faceted_search_ui_build_categories($search, $index, 0, $max_count);
    if (count($categories) > 0 || $facet->is_active()) {
      $content = theme('faceted_search_ui_facet_heading', $search->get_env_id(), $search->ui_state, $search->get_facets(), $index, 'guided');
      $content .= theme('faceted_search_ui_categories', $facet, $categories, $search->ui_state['stage']);
      $facet_content[] = theme('faceted_search_ui_facet_wrapper', $search->get_env_id(), $facet, 'guided', $content);
    }
  }
  return theme('faceted_search_ui_guided_search', $search, $facet_content);
}

/**
 * Display the facets related to the specified node.
 *
 * Facets with the same key and id are grouped under the same label (instead of
 * repeating the label).
 */
function faceted_search_ui_related_block($env_id, $node) {
  $types = faceted_search_types($env_id);
  if (!isset($types[$node->type])) {
    return; // This node type is not used in the current environment.
  }

  // Load settings for all enabled facets in this search environment.
  $all_settings = faceted_search_load_facet_settings($env_id);
    
  // Make a filter with all enabled facets.
  $filter = faceted_search_get_facet_filter($all_settings);
  
  // Collect all facets relevant to this node.
  $facets = array();
  foreach (module_implements('faceted_search_collect') as $module) {
    $hook = $module .'_faceted_search_collect';
    $hook($facets, 'node', $env_id, $filter, $node);
  }

  // Prepare facets for use, assigning them their settings are sorting them.
  faceted_search_prepare_facets($facets, $all_settings);
  
  // Organize facets so that those that have a common label are grouped together.
  $groups = array(); // All groups of facets.
  $index = -1; // Index of the current group of facets.
  $last_facet = '';
  foreach ($facets as $facet) {
    $current_facet = $facet->get_key() .'-'. $facet->get_id();
    if ($current_facet != $last_facet) {
      $index++; // Start a new group.
    }
    $groups[$index][] = $facet;
    $last_facet = $current_facet;
  }

  return theme('faceted_search_ui_related_'. faceted_search_variable_get($env_id, 'related_style', 'list_ungrouped'), $env_id, $node, $groups);
}

/**
 * Discover the available display styles by invoking
 * hook_faceted_search_ui_style_info().
 *
 * @return
 *   An associative array keyed on style id. The id contains the module's name
 *   to ensure it is globally unique. The value of each key is an array
 *   containing information about the style: 'label', 'callback', 'args'.
 *
 * @see faceted_search_ui_views_faceted_search_ui_style_info()
 */
function faceted_search_ui_style_list() {
  static $styles;
  if (!isset($styles)) {
    $styles = array();
    foreach (module_implements('faceted_search_ui_style_info') as $module) {
      $function = $module .'_faceted_search_ui_style_info';
      if ($module_styles = $function()) {
        foreach ($module_styles as $id => $style) {
          // Add each of the styles provided by the module to the global array,
          // prepending the style id with the module name.
          $styles[$module .':'. $id] = $style;
        }
      }
    }  
  }
  return $styles;
}

/**
 * Indicate how to present search results.
 *
 * @return Id of the style to use.
 */
function faceted_search_ui_get_style($search) {
  if (faceted_search_variable_get($search->get_env_id(), 'results_style_selective_extracts', TRUE) && $search->get_keywords()) {
    return 'faceted_search_ui:extracts';
  }
  else {
    return faceted_search_variable_get($search->get_env_id(), 'results_style', 'faceted_search_ui:teasers');
  }
}

/**
 * Display sort options.
 */
function faceted_search_ui_sort_block($search) {
  $ui_state = $search->ui_state;
  if ($ui_state['stage'] == 'facet') {
    list($index, $facet) = $search->get_facet_by_id($search->ui_state['facet-key'], $search->ui_state['facet-id']);
    $sort_options = $facet->get_sort_options();
    if (count($sort_options) > 1) {
      $sort_links = array();
      foreach ($sort_options as $option => $name) {
        $attributes = $search->ui_state['facet-sort'] == $option ? array('class' => 'active') : array();
        $ui_state['facet-sort'] = $option;
        $path = faceted_search_ui_build_path($search->get_env_id(), $ui_state, $search->get_text());
        $sort_links[] = l($name, $path, $attributes);
      }
      return theme('faceted_search_ui_sort_options', $sort_links);
    }
  }
}

/**
 * Sets the page title.
 */
function faceted_search_ui_set_title($search) {
  if ($search->get_text()) {
    $labels = array();
    foreach ($search->get_facets() as $facet) {
      if ($facet->is_active()) {
        $category = $facet->get_active_category();
        $labels[] = check_plain(strip_tags($category->get_label()));
      }
    }
  }
  $title = faceted_search_variable_get($search->get_env_id(), 'title', t('Search'));
  if ($labels) {
    drupal_set_title(t('@title: @terms', array('@title' => $title, '@terms' => implode(', ', $labels))));
  }
  else {
    drupal_set_title(check_plain($title));
  }
}

/**
 * Format the results of the specified search according to the current display
 * style.
 */
function faceted_search_ui_format_results($search) {
  $styles = faceted_search_ui_style_list();
  $style = faceted_search_ui_get_style($search);
  if (method_exists($styles[$style], 'format_results')) {
    return $styles[$style]->format_results($search);
  }
}
  
/**
 * Render the search form.
 */
function faceted_search_ui_form($search) {
  $form['basic']['keywords']['and'] = array(
    '#type' => 'textfield',
    '#title' => $search->ui_state['stage'] == 'select' ? t('With all of the words') : '',
    '#default_value' => '',
    '#size' => 20,
    '#maxlength' => 255,
  );
  $ui_state = $search->ui_state;
  $current_stage = $ui_state['stage'];
  if ($current_stage == 'select') {
    $form['advanced'] = array(
      '#type' => 'fieldset',
      '#title' => t('Advanced search'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#attributes' => array('class' => 'faceted-search-advanced'),
    );
    $form['advanced']['keywords']['phrase'] = array(
      '#type' => 'textfield',
      '#title' => t('With the exact phrase'),
      '#default_value' => '',
      '#size' => 20,
      '#maxlength' => 255,
    );
    $form['advanced']['keywords']['or'] = array(
      '#type' => 'textfield',
      '#title' => t('With at least one of the words'),
      '#default_value' => '',
      '#size' => 20,
      '#maxlength' => 255,
    );
    $form['advanced']['keywords']['not'] = array(
      '#type' => 'textfield',
      '#title' => t('Without the words'),
      '#default_value' => '',
      '#size' => 20,
      '#maxlength' => 255,
    );
  }
  if ($search->get_text() != '') {
    $form['text'] = array(
      '#type' => 'hidden',
      '#value' => $search->get_text(),
    );
    $form['refine'] = array(
      '#type' => 'radios',
      '#title' => '',
      '#default_value' => faceted_search_variable_get($search->get_env_id(), 'keyword_mode', 'new'),
      '#options' => array('new' => t('New search'), 'refine' => t('Search within results')),
    );
  }
  $form['env_id'] = array(
    '#type' => 'hidden',
    '#value' => $search->get_env_id(),
  );
  $form['stage'] = array(
    '#type' => 'hidden',
    '#value' => $current_stage == 'select' ? 'results' : $current_stage,
  );
  $form['facet-key'] = array(
    '#type' => 'hidden',
    '#value' => $search->ui_state['facet-key'],
  );
  $form['facet-id'] = array(
    '#type' => 'hidden',
    '#value' => $search->ui_state['facet-id'],
  );
  $form['facet-sort'] = array(
    '#type' => 'hidden',
    '#value' => $search->ui_state['facet-sort'],
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  if ($current_stage == 'select') {
    if ($search->get_text()) {
      // Add a Back to results button if we're in faceted search's select page.
      $ui_state['stage'] = 'results';
      $path = faceted_search_ui_build_path($search->get_env_id(), $ui_state, $search->get_text());
      $form['go-results']['#value'] = l(t('Back to results'), $path);
    }
    elseif (faceted_search_variable_get($search->get_env_id(), 'start_page', faceted_search_variable_get($search->get_env_id(), 'base_path', '')) != $_GET['q']) {
      // Add a Cancel button if there's a 'start page' other than faceted search's select page.
      $ui_state['stage'] = 'results';
      $path = faceted_search_ui_build_path($search->get_env_id(), $ui_state, $search->get_text());
      $form['go-results']['#value'] = l(t('Cancel'), $path);
    }
  }
  else {
    $ui_state['stage'] = 'select';
    $path = faceted_search_ui_build_path($search->get_env_id(), $ui_state, $search->get_text());
    $form['go-select']['#value'] = l(t('More options'), $path);
  }
  
  return $form;
}

/**
 * Process a search form submission.
 */
function faceted_search_ui_form_submit($form_id, $form_values) {
  // Based on node_search_validate() - BEGIN
  if ($form_values['and'] != '') {
    if (preg_match_all('/ ("[^"]+"|[^" ]+)/i', ' '. $form_values['and'], $matches)) {
      $new_text .= ' '. implode(' ', $matches[1]);
    }
  }
  if ($form_values['or'] != '') {
    if (preg_match_all('/ ("[^"]+"|[^" ]+)/i', ' '. $form_values['or'], $matches)) {
      $new_text .= ' '. implode(' OR ', $matches[1]);
    }
  }
  if ($form_values['not'] != '') {
    if (preg_match_all('/ ("[^"]+"|[^" ]+)/i', ' '. $form_values['not'], $matches)) {
      $new_text .= ' -'. implode(' -', $matches[1]);
    }
  }
  if ($form_values['phrase'] != '') {
    $new_text .= ' "'. str_replace('"', ' ', $form_values['phrase']) .'"';
  }
  // Based on node_search_validate() - END

  // Combine pre-exiting text with new one
  if ($form_values['refine'] == 'new') {
    $text = trim($new_text);
  }
  else {
    $text = trim($form_values['text'] . $new_text);
  }

  // Define resulting path. Note: $form_values has the same keys as the usual
  // $ui_state argument.
  return faceted_search_ui_build_path($form_values['env_id'], $form_values, $text);
}

/**
 * Build a search path with the specified components. If $text is not
 * specified, the search text path component is generated from $facets.
 */
function faceted_search_ui_build_path($env_id, $ui_state, $text, $facets = array()) {
  if (!$text && $facets) {
    $text = faceted_search_build_text($facets);
  }
  
  if (!$text && $ui_state['stage'] == 'results') {
    // No search text, go to the start page.
    return faceted_search_variable_get($env_id, 'start_page', faceted_search_variable_get($env_id, 'base_path', ''));
  }

  if ($ui_state['stage'] == 'select') {
    $stage = '';
  }
  else {
    $stage = '/'. $ui_state['stage'];
  }
  
  $facet = '';
  $facet_sort = '';
  if (($ui_state['stage'] == 'facet' || $ui_state['stage'] == 'categories') && $ui_state['facet-key'] && $ui_state['facet-id']) {
    $facet = "/{$ui_state['facet-key']}:{$ui_state['facet-id']}";

    if ($ui_state['stage'] == 'facet' && $ui_state['facet-sort']) {
      $facet_sort = "/${ui_state['facet-sort']}";
    }
    else {
      $facet_sort = '/-';
    }
  }

  $base_path = faceted_search_variable_get($env_id, 'base_path', '');
  return "{$base_path}{$stage}{$facet}{$facet_sort}/{$text}";
}

/**
 * Build the remover path for a given facet.
 *
 * @param $ui_state
 *   The current state of the user interface.
 *
 * @param $env_id
 *   The id of the search environment to use.
 *
 * @param $facets
 *   The facets to take into account in the remover's links.
 *
 * @param $index
 *   Index of the facet whose remover shall be built.
 */
function faceted_search_ui_build_remover_path($env_id, $ui_state, $facets, $index) {
  // Remove current facet for remover.
  unset($facets[$index]); 
  // Switch to results stage.
  if ($ui_state['stage'] == 'select' || $ui_state['stage'] == 'facet') {
    $ui_state['stage'] = 'results';
  }
  return faceted_search_ui_build_path($env_id, $ui_state, '', $facets);
}

/**
 * Build the breadcrumb of a facet according to its active path.
 *
 * @param $ui_state
 *   The current state of the user interface.
 *
 * @param $env_id
 *   The id of the search environment to use.
 *
 * @param $facets
 *   The facets to take into account in the breadcrumb's links.
 *
 * @param $index
 *   Index of the facet whose breadcrumb shall be built.
 *
 * @param $breadcrumb
 *   Array of initial components (or prefix components) of the breadcrumb, if
 *   any is desired.
 *
 * @param $context
 *   The caller's context (either 'guided', 'current', or 'related').
 *
 * @return
 *   Array of breadcrumb components.
 */
function faceted_search_ui_build_breadcrumb($env_id, $ui_state, $facets, $index, $breadcrumb = array(), $context = 'guided') {
  $facet = $facets[$index];
  if ($facet->is_active()) {
    // Replace the current facet with a clone for active category manipulations
    // (to avoid manipulating the original facet).
    $facets[$index] = drupal_clone($facet);
    
    $path = array();
    foreach ($facet->get_active_path() as $category_index => $category) {
      $path[] = $category;
      // Replace active category within the facet
      $facets[$index]->set_active_path($path);
      // Switch to results stage.
      if ($ui_state['stage'] == 'select') {
        $ui_state['stage'] = 'results';
      }
      $link = faceted_search_ui_build_path($env_id, $ui_state, '', $facets);
      $breadcrumb[] = l($category->get_label(), $link);
    }
    if ($category && $context != 'related') {
      // The last category needs not be a link to itself since it is already in
      // the current search.
      // Note: theme_faceted_search_keyword_or_label() uses <em> in the label.
      $breadcrumb[count($breadcrumb) - 1] = filter_xss($category->get_label(), array('em', 'strong')); 
    }
  }

  return $breadcrumb;
}

/**
 * Build the subcategory links of a facet.
 *
 * @param $search
 *   The search context.
 *
 * @param $index
 *   Index of the facet within the search context.
 *
 * @param $from
 *   Ordinal number of the first category to load. Numbering starts at 0.
 *
 * @param $max_count
 *   Number of categories to load.
 *
 * @param $links
 *   TRUE to generate category links, FALSE to generate text.
 */
function faceted_search_ui_build_categories($search, $index, $from = NULL, $max_count = NULL, $links = TRUE) {
  $facets = $search->get_facets();
  $facet = $facets[$index];
  $facet->set_sort($search->ui_state['facet-sort']);
  
  // Load the categories. If a limit is used, we load one extra category in
  // order to determine whether a 'more' link needs to be displayed.
  $categories = $search->load_categories($facet, $from, (isset($max_count) ? $max_count + 1 : $max_count));

  // Replace the facet with a clone to allow active category manipulations (to
  // avoid manipulating the original facet).
  $facets[$index] = drupal_clone($facet);

  $ui_state = $search->ui_state;
  $ui_state['stage'] = 'results';
  $ui_state['facet-key'] = '';
  $ui_state['facet-id'] = '';
  $ui_state['facet-sort'] = '';

  // Build links to categories.
  // TODO: Separate into alphabetical groups (with first letter of each category label), if configured to do so
  $items = array();
  foreach ($categories as $category_index => $category) {
    if (isset($max_count) && $category_index == $max_count) {
      break; // Do not theme the extra category.
    }
    if ($links) {
      $active_path = $facet->get_active_path();
      $active_path[] = $category;
      // Replace active path in the facet
      $facets[$index]->set_active_path($active_path);
      $path = faceted_search_ui_build_path($search->get_env_id(), $ui_state, '', $facets);
    }
    $items[] = theme('faceted_search_ui_category', $category, $path);
  }

  // Add the 'more...' link.
  if ($search->ui_state['stage'] != 'facet' && isset($max_count) && count($categories) > $max_count) {
    if ($links) {
      $ui_state['stage'] = 'facet';
      $ui_state['facet-key'] = $facet->get_key();
      $ui_state['facet-id'] = $facet->get_id();
      $ui_state['facet-sort'] = $facet->get_sort();
      $path = faceted_search_ui_build_path($search->get_env_id(), $ui_state, $search->get_text());
    }
    $items[] = theme('faceted_search_ui_more', $path);
  }
  
  return $items;
}

/**
 * Add the default stylesheet.
 */
function faceted_search_ui_add_css() {
  drupal_add_css(drupal_get_path('module', 'faceted_search') .'/faceted_search_ui.css');
}

/**
 * Add scripts for tooltips.
 */
function faceted_search_ui_add_tooltips($env_id) {
  // If tooltips are enabled, add the necessary scripts.
  if (faceted_search_variable_get($env_id, 'tooltips', FALSE)) {
    $path = drupal_get_path('module', 'faceted_search');
    drupal_add_js($path .'/lib/dimensions/jquery.dimensions.pack.js');
    drupal_add_js($path .'/jquery.faceted_search_ui.js');
  }
}

/**
 * Provides the 'extracts' display style for search results.
 */
class faceted_search_ui_extract_style {

  /**
   * Return the name of this style.
   */
  function get_label() {
    return t('Extracts');
  }

  /**
   * Format the search results to display node extracts showing relevant
   * keywords.
   */
  function format_results($search) {
    drupal_add_css(drupal_get_path('module', 'search') .'/search.css');
    
    $found_items = $search->load_results(variable_get('default_nodes_main', 10));
      
    // Taken from node_search() (node.module 1.764) - BEGIN
    $results = array();
    foreach ($found_items as $item) {
      // Build the node body.
      $node = node_load($item->nid);
      $node = node_build_content($node, FALSE, FALSE);
      $node->body = drupal_render($node->content);

      // Fetch comments for snippet
      $node->body .= module_invoke('comment', 'nodeapi', $node, 'update index');
      // Fetch terms for snippet
      $node->body .= module_invoke('taxonomy', 'nodeapi', $node, 'update index');

      $extra = node_invoke_nodeapi($node, 'search result');
      $results[] = array(
        'link' => url('node/'. $item->nid, NULL, NULL, TRUE),
        'type' => node_get_types('name', $node),
        'title' => $node->title,
        'user' => theme('username', $node),
        'date' => $node->changed,
        'node' => $node,
        'extra' => $extra,
        'score' => $item->score,
        'snippet' => search_excerpt($search->get_keywords(), $node->body));
    }
    // Taken from node_search() - END
    
    return theme('search_page', $results, 'node');
  }
}

/**
 * Provides the 'teasers' display style for search results.
 */
class faceted_search_ui_teaser_style {

  /**
   * Return the name of this style.
   */
  function get_label() {
    return t('Teasers');
  }

  /**
   * Format the search results to display node teasers.
   */
  function format_results($search) {
    $limit = variable_get('default_nodes_main', 10);
    $found_items = $search->load_results($limit);
    
    foreach ($found_items as $item) {
      $output .= node_view(node_load($item->nid), TRUE);
    }      
    return $output . theme('pager', NULL, $limit);
  }
}

/**
 * Render a faceted search page.
 *
 * @param $search
 *   The search context.
 * @param $content
 *   The page's content.
 */
function theme_faceted_search_ui_page($search, $content) {
  $classes = array(
    'faceted-search-page',
    'faceted-search-stage-'. $search->ui_state['stage'],
    'faceted-search-env-'. faceted_search_variable_get($search->get_env_id(), 'name', 'faceted_search'),
  );
  return '<div class="'. implode(' ', $classes) .'">'. $content .'</div>'."\n";
}

/**
 * Render a wrapper around a facet.
 *
 * @param $env_id
 *   The environment to which the facet belongs.
 * @param $facet
 *   The facet object.
 * @param $context
 *   The caller's context (either 'guided', 'current', 'related', or
 *   'categories').
 * @param $content
 *   The facet's content (heading, categories, etc.)
 */
function theme_faceted_search_ui_facet_wrapper($env_id, $facet, $context, $content) {
  $classes = array(
    'faceted-search-facet', // Note: Tooltips rely on this class.
    'faceted-search-env-'. faceted_search_variable_get($env_id, 'name', $env_id),
    'faceted-search-facet--'. check_plain($facet->get_key() .'--'. $facet->get_id()), // Note: Tooltips rely on this class.
    'faceted-search-facet-'. ($facet->is_active() && $context != 'related' ? 'active' : 'inactive'),
    'faceted-search-'. $context,
  );
  return '<div class="'. implode(' ', $classes) .'">'. $content .'</div>'."\n";
}

/**
 * Render the facet identified by $index. This displays the facet's label,
 * active path, and active category.
 *
 * @param $env_id
 *   Id of the search environment to use.
 * @param $context
 *   The caller's context (either 'guided', 'current', or 'related').
 * @param $show_label
 *   Determines whether to display the facet's label. True by default.
 */
function theme_faceted_search_ui_facet_heading($env_id, $ui_state, $facets, $index, $context, $show_label = TRUE) {
  $facet = $facets[$index];
  $remover_path = faceted_search_ui_build_remover_path($env_id, $ui_state, $facets, $index);
  
  if ($context == 'current') {
    $output .= theme('faceted_search_ui_remover_link_current_search', $remover_path) .' ';
  }

  // Render the facet's label (except for keyword facets).
  if ($show_label && $facet->get_key() != 'keyword') {
    $output .= theme('faceted_search_ui_facet_label', $facets, $index, $context);
    if ($facet->is_active()) {
      $output .= ': ';
    }
  }

  // Render path to the facet's active category.
  if ($facet->is_active()) {
    $breadcrumb = array();
    if ($context == 'guided') {
      $breadcrumb[] = theme('faceted_search_ui_remover_link_guided_search', $remover_path);
    }
    $breadcrumb = faceted_search_ui_build_breadcrumb($env_id, $ui_state, $facets, $index, $breadcrumb, $context);
    $output .= theme('faceted_search_ui_breadcrumb', $breadcrumb);
  }

  return $output;
}

function theme_faceted_search_ui_categories($facet, $categories, $stage) {
  if (count($categories)) {
    switch ($stage) {
      case 'select':
      case 'categories':
        $column_count = 2;
        break;
      case 'facet':
        $column_count = 4;
        break;
      default:
        $column_count = 1;
    }
    if ($column_count > 1) {
      $columns = array_chunk($categories, ceil(count($categories) / $column_count));
      $row = array();
      for ($column_index = 0; $column_index < $column_count && $column_index < count($columns); $column_index++) {
        $row[] = theme('item_list', $columns[$column_index]);
      }
      // Ensure a consistent number of columns
      while ($column_index < $column_count) {
        $column_index++;
        $row[] = '';
      }
      return theme('table', array(), array($row), array('class' => 'faceted-search'));
    }
    else {
      return theme('item_list', $categories);
    }
  }
}

function theme_faceted_search_ui_facet_label($facets, $index, $label) {
  // Note: theme_faceted_search_keyword_or_label() uses <em> in the label.
  return '<h3>'. filter_xss($facets[$index]->get_label(), array('em', 'strong')) .'</h3>';
}

function theme_faceted_search_ui_category($category, $path) {
  // Note: Tooltips rely on class 'faceted-search-category'.
  return '<span class="faceted-search-category">'. ($path ? l($category->get_label(), $path) : check_plain($category->get_label())) .' ('. $category->get_count() .')</span>';
}

function theme_faceted_search_ui_more($path) {
  if ($path) {
    return l(t('more...'), $path, array('class' => 'faceted-search-more'));
  }
  else {
    return '<span class="faceted-search-more">'. t('more...') .'</span>';
  }
}

function theme_faceted_search_ui_remover_link_guided_search($path) {
  return l(t('all'), $path);
}

function theme_faceted_search_ui_remover_link_current_search($path) {
  // TODO: nice default icon instead of 'x'
  return l('[&times;]', $path, array('title' => t('Remove this term')), NULL, NULL, FALSE, TRUE);
}

function theme_faceted_search_ui_breadcrumb($breadcrumb) {
  return implode(' &raquo; ', $breadcrumb);
}

function theme_faceted_search_ui_sort_options($options) {
  return '<p>'. t('Sort by: !options', array('!options' => implode(' | ', $options))) .'</p>';
}

function theme_faceted_search_ui_stage_results($results) {
  global $pager_total, $pager_total_items, $pager_page_array;
  if ($pager_total_items[0] > 0) {
    $limit = variable_get('default_nodes_main', 10);
    $from = $pager_page_array[0] * $limit + 1;
    $to = min(($pager_page_array[0] + 1) * $limit, $pager_total_items[0]);
    $total = $pager_total_items[0];
    
    if ($total == 1) {
      $numbering = t('1 result');
    }
    elseif ($from == $to) {
      $numbering = t('Result @to of @total', array('@to' => $to, '@total' => $total));
    }
    elseif ($total <= $limit) {
      $numbering = t('@total results', array('@total' => $pager_total_items[0]));
    }
    else {
      $numbering = t('Results @from - @to of @total', array('@from' => $from, '@to' => $to, '@total' => $total));
    }
    
    $numbering = '<div class="faceted-search-numbering">'. $numbering .'</div>';
    return $numbering . theme('box', t('Results'), $results);
  }
  else {
    return theme('box', t('Your search yielded no results'), search_help('search#noresults'));
  }
}

function theme_faceted_search_ui_stage_select($search, $keyword_block_content, $guided_block_content) {
  if ($keyword_block_content) {
    $form['keyword'] = array(
      '#type' => 'fieldset',
      '#title' => t('Keyword search'),
      '#value' => $keyword_block_content,
      '#weight' => 0,
      '#attributes' => array('class' => 'faceted-search-keyword'),
    );
  }
  if ($guided_block_content) {
    $form['guided'] = array(
      '#type' => 'fieldset',
      '#title' => t('Guided search'),
      '#value' => $guided_block_content,
      '#weight' => 1,
      '#attributes' => array('class' => 'faceted-search-guided'),
    );
  }
  return drupal_render($form);
}

function theme_faceted_search_ui_stage_facet($search, $index, $facet, $categories) {
  $content .= '<p>'. ($search->get_text() ? t('Click a term to refine your current search.') : t('Click a term to initiate a search.')) .'</p>';
  $content .= theme('faceted_search_ui_facet_heading', $search->get_env_id(), $search->ui_state, $search->get_facets(), $index, 'guided');
  $content .= theme('faceted_search_ui_categories', $facet, $categories, $search->ui_state['stage']);
  $content = theme('faceted_search_ui_facet_wrapper', $search->get_env_id(), $facet, 'guided', $content);
  return theme('faceted_search_ui_page', $search, $content);
}

/**
 * Renders a set of facets.
 *
 * @param $search
 *   The search context.
 *
 * @param $facets
 *   Array of individually rendered facets.
 */
function theme_faceted_search_ui_guided_search($search, $facets) {
  if (count($facets)) {
    $output .= '<p>'. ($search->get_text() ? t('Click a term to refine your current search.') : t('Click a term to initiate a search.')) .'</p>';
    if ($search->ui_state['stage'] == 'select') {
      // Show facets in two columns in stage 'select'.
      $column_count = 2;
      $columns = array_chunk($facets, ceil(count($facets) / $column_count));
      $row = array();
      for ($column_index = 0; $column_index < $column_count && $column_index < count($columns); $column_index++) {
        $row[] = implode('', $columns[$column_index]);
      }
      // Ensure a consistent number of columns
      while ($column_index < $column_count) {
        $column_index++;
        $row[] = '';
      }
      $output .= theme('table', array(), array($row), array('class' => 'faceted-search'));
    }
    else {
      // In other stages, just concat all the facets.
      $output .= implode('', $facets);
    }
  }
  return $output;
}

/**
 * Display a list of facets related to a node in a list.
 *
 * @param $env_id
 *   The environment to use.
 * @param $node
 *   The node whose related categories are being themed.
 * @param $groups
 *   Groups of facets, where facets within a group have a common label.
 */
function theme_faceted_search_ui_related_list_ungrouped($env_id, $node, $groups) {
  $output = '';
  foreach ($groups as $group) {
    foreach ($group as $facet) {
      $rendered_facet = theme('faceted_search_ui_facet_heading', $env_id, _faceted_search_ui_defaults(), array($facet), 0, 'related');
      $output .= theme('faceted_search_ui_facet_wrapper', $env_id, $facet, 'related', $rendered_facet);
    }
  }
  return $output;
}

/**
 * Display a list of facets related to a node in a list, with categories grouped by facet.
 *
 * @param $env_id
 *   The environment to use.
 * @param $node
 *   The node whose related categories are being themed.
 * @param $groups
 *   Groups of facets, where facets within a group have a common label.
 */
function theme_faceted_search_ui_related_list_grouped($env_id, $node, $groups) {
  $output = '';
  foreach ($groups as $group) {
    $first = TRUE;
    foreach ($group as $facet) {
      if ($first) {
        $rendered_facets = array(); // Start a new group.
        $label = theme('faceted_search_ui_facet_label', array($facet), 0, 'related');
      }
      $rendered_facets[] = theme('faceted_search_ui_facet_heading', $env_id, _faceted_search_ui_defaults(), array($facet), 0, 'related', FALSE);
      $first = FALSE;
    }
    $output .= theme('faceted_search_ui_facet_wrapper', $env_id, $facet, 'related', $label . theme('item_list', $rendered_facets));
  }
  return $output;
}

/**
 * Display a list of facets related to a node in a table.
 *
 * @param $env_id
 *   The environment to use.
 * @param $node
 *   The node whose related categories are being themed.
 * @param $groups
 *   Groups of facets, where facets within a group have a common label.
 */
function theme_faceted_search_ui_related_table($env_id, $node, $groups) {
  $items = array();
  foreach ($groups as $group) {
    $first = TRUE;
    foreach ($group as $facet) {
      $rendered_facet = theme('faceted_search_ui_facet_heading', $env_id, _faceted_search_ui_defaults(), array($facet), 0, 'related', FALSE);
      $rendered_facet = theme('faceted_search_ui_facet_wrapper', $env_id, $facet, 'related', $rendered_facet);
      if ($first) {
        // Output a row with two cells: the label and the first facet of the group.
        $label = theme('faceted_search_ui_facet_label', array($facet), 0, 'related');
        $label = theme('faceted_search_ui_facet_wrapper', $env_id, $facet, 'related', $label);
        $items[] = array( // Row.
          'data' => array(
            array( // 1st cell.
              'data' => $label,
              'rowspan' => count($group)), 
            $rendered_facet, // 2nd cell.
          ),
          'class' => 'faceted-search-first', // Mark the first row of a group.
        );
      }
      else {
        // Output a row with a single cell containing the facet.
        $items[] = array( // Row.
          'data' => array(
            $rendered_facet // 1st (and only) cell.
          ),
          'class' => 'faceted-search-next',
        );
      }
      $first = FALSE;
    }
  }
  return theme('table', array(), $items, array('class' => 'faceted-search'));
}

/**
 * Return the values representing the user interface's default state.
 */
function _faceted_search_ui_defaults() {
  return array(
    'stage' => 'results',
    'facet-key' => '',
    'facet-id' => '',
    'facet-sort' => '',
  );
}

